'use strict';
$(function(){
	//搜索框
	$(".search-seek").on("click",function(){
		$(this).stop(true).animate({width: "74%"});
		$(".search-quiz").fadeOut(400);
	})
	$("body").on("blur",".search-seek",function(){
		$(this).stop(true).animate({width: "56%"});
		$(".search-quiz").fadeIn(400);
        $("body").removeClass("h");
	})
    $(".search-seek-input").on("input",function(){
        $(".seek").show();
        $("body").addClass("h");
    })
    $(".seek-aspect-side").on("click",function(){
        $(".search-seek-input").val($(this).text());
        $(".seek").hide();
    })
    $(".seek").on("click",function(){
        $(".seek").hide();
    })
    //详情
    $(".card-comment-center").on("click",function(){
        $(".reply-place").stop(true).animate({"left":0});
        $(".go").stop(true).animate({"left":0});
    })
    $(".card-name").on("click",function(){
        $(".reply-place").stop(true).animate({"left":0});
        $(".go").stop(true).animate({"left":0});
    })
    $(".go-back").on("click",function(){
        $(".reply-place").stop(true).animate({"left":"100%"});
        $(".go").stop(true).animate({"left":"100%"});
    })
    //无刷新加载
    $(".card-writer-more").on("click",function(){
        $(this).hide();
    })
    //排序
    $(".sort-heat").eq(0).addClass("h");
    $(".sort-heat").on("click",function(){
        $(this).addClass("h").siblings(".sort-heat").removeClass("h");
    })
    $(".content-time").addClass("h");
    //回复的大小不一
    $(".reply-top-head").eq(0).addClass("h");
    $(".reply-top-ranking").eq(0).addClass("h");
    $(".reply-writer:last").eq(0).addClass("h");
    $(".reply-writer-more:last").show();
    $(".reply-writer-more").on("click",function(){
        $(this).hide();
        $(".reply-writer:last").eq(0).removeClass("h");
    })
    //跳转登录
    $(".card-comment-left,.card-top-head,.go-omit,.topic-writer-top-head,.topic-comment-content,.reply-top-heat").on("click",function(){
		location.href="gongzuoya-please-login.html"
	})
})